--
-- PostgreSQL database dump
--

\restrict AddwHtsQxcNHgV6VMrpf3QAzsFBcNHGTdlbLKIsoRZn1Tz6cjOEpEqx0iGsuAeM

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.return_requests DROP CONSTRAINT IF EXISTS fkqmtolfa50ie1jxfsak1e8jnkb;
ALTER TABLE IF EXISTS ONLY public.cart_items DROP CONSTRAINT IF EXISTS fkpcttvuq4mxppo8sxggjtn5i2c;
ALTER TABLE IF EXISTS ONLY public.products DROP CONSTRAINT IF EXISTS fkog2rp4qthbtt2lfyhfo32lsw9;
ALTER TABLE IF EXISTS ONLY public.order_items DROP CONSTRAINT IF EXISTS fkocimc7dtr037rh4ls4l95nlfi;
ALTER TABLE IF EXISTS ONLY public.audit_logs DROP CONSTRAINT IF EXISTS fkjs4iimve3y0xssbtve5ysyef0;
ALTER TABLE IF EXISTS ONLY public.return_requests DROP CONSTRAINT IF EXISTS fkbski88d6kewx0cbj5pk7nes01;
ALTER TABLE IF EXISTS ONLY public.order_items DROP CONSTRAINT IF EXISTS fkbioxgbv59vetrxe0ejfubep1w;
ALTER TABLE IF EXISTS ONLY public.carts DROP CONSTRAINT IF EXISTS fkb5o626f86h46m4s7ms6ginnop;
ALTER TABLE IF EXISTS ONLY public.return_requests DROP CONSTRAINT IF EXISTS fk6pd9hi2rbbct43io2pgcma1sh;
ALTER TABLE IF EXISTS ONLY public.orders DROP CONSTRAINT IF EXISTS fk32ql8ubntj5uh44ph9659tiih;
ALTER TABLE IF EXISTS ONLY public.cart_items DROP CONSTRAINT IF EXISTS fk1re40cjegsfvw58xrkdp6bac6;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.categories DROP CONSTRAINT IF EXISTS ukt8o6pivur7nn124jehx7cygw5;
ALTER TABLE IF EXISTS ONLY public.cart_items DROP CONSTRAINT IF EXISTS uk_cart_product;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk6dotkott2kjsp8vw4d0m25fb7;
ALTER TABLE IF EXISTS ONLY public.carts DROP CONSTRAINT IF EXISTS uk64t7ox312pqal3p7fg9o503c2;
ALTER TABLE IF EXISTS ONLY public.return_requests DROP CONSTRAINT IF EXISTS return_requests_pkey;
ALTER TABLE IF EXISTS ONLY public.products DROP CONSTRAINT IF EXISTS products_pkey;
ALTER TABLE IF EXISTS ONLY public.orders DROP CONSTRAINT IF EXISTS orders_pkey;
ALTER TABLE IF EXISTS ONLY public.order_items DROP CONSTRAINT IF EXISTS order_items_pkey;
ALTER TABLE IF EXISTS ONLY public.categories DROP CONSTRAINT IF EXISTS categories_pkey;
ALTER TABLE IF EXISTS ONLY public.carts DROP CONSTRAINT IF EXISTS carts_pkey;
ALTER TABLE IF EXISTS ONLY public.cart_items DROP CONSTRAINT IF EXISTS cart_items_pkey;
ALTER TABLE IF EXISTS ONLY public.audit_logs DROP CONSTRAINT IF EXISTS audit_logs_pkey;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.return_requests;
DROP TABLE IF EXISTS public.products;
DROP TABLE IF EXISTS public.orders;
DROP TABLE IF EXISTS public.order_items;
DROP TABLE IF EXISTS public.categories;
DROP TABLE IF EXISTS public.carts;
DROP TABLE IF EXISTS public.cart_items;
DROP TABLE IF EXISTS public.audit_logs;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(2000),
    entity_id bigint,
    entity_type character varying(255) NOT NULL,
    user_id bigint
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT cart_items_quantity_check CHECK ((quantity >= 1))
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(1000),
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT order_items_quantity_check CHECK ((quantity >= 1))
);


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    delivery_address character varying(1000),
    order_status character varying(255) NOT NULL,
    order_type character varying(255) NOT NULL,
    pickup_date date,
    pickup_time_slot character varying(255),
    total_amount numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT orders_order_status_check CHECK (((order_status)::text = ANY ((ARRAY['PLACED'::character varying, 'CONFIRMED'::character varying, 'PREPARING'::character varying, 'READY_FOR_PICKUP'::character varying, 'OUT_FOR_DELIVERY'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT orders_order_type_check CHECK (((order_type)::text = ANY ((ARRAY['PICKUP'::character varying, 'DELIVERY'::character varying])::text[])))
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(2000),
    image_url character varying(1000),
    name character varying(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    updated_at timestamp(6) without time zone,
    category_id bigint NOT NULL,
    CONSTRAINT products_stock_check CHECK ((stock >= 0))
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.return_requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    reason character varying(1000) NOT NULL,
    staff_comment character varying(1000),
    status character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    order_id bigint NOT NULL,
    user_id bigint NOT NULL,
    note character varying(1000),
    quantity integer NOT NULL,
    order_item_id bigint NOT NULL,
    CONSTRAINT return_requests_quantity_check CHECK ((quantity >= 1)),
    CONSTRAINT return_requests_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT return_requests_type_check CHECK (((type)::text = ANY ((ARRAY['RETURN'::character varying, 'EXCHANGE'::character varying])::text[])))
);


--
-- Name: return_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.return_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(20),
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'STAFF'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.audit_logs (id, action, created_at, description, entity_id, entity_type, user_id) FROM stdin;
\.


--
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cart_items (id, quantity, cart_id, product_id) FROM stdin;
\.


--
-- Data for Name: carts; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.carts (id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.categories (id, active, created_at, description, name, updated_at) FROM stdin;
907	t	2026-08-23 00:43:34.749924	Fresh seasonal and exotic organic fruits	Fruits	2026-08-23 00:43:34.749924
908	t	2026-08-23 00:43:34.798451	Farm fresh daily vegetables, greens, and root crops	Vegetables	2026-08-23 00:43:34.798451
909	t	2026-08-23 00:43:34.805112	Fresh milk, butter, cheese, paneer, and curd	Dairy	2026-08-23 00:43:34.805112
910	t	2026-08-23 00:43:34.811059	Tea, coffee, fruit juices, and cold beverages	Beverages	2026-08-23 00:43:34.811059
911	t	2026-08-23 00:43:34.81711	Biscuits, savory namkeen, chips, and chocolates	Snacks	2026-08-23 00:43:34.817711
912	t	2026-08-23 00:43:34.824986	Freshly baked artisan breads, cookies, and buns	Bakery	2026-08-23 00:43:34.824986
913	t	2026-08-23 00:43:34.829983	Soaps, oral care, body wash, and hair care	Personal Care	2026-08-23 00:43:34.829983
914	t	2026-08-23 00:43:34.837187	Detergents, cleaners, dishwash, and home essentials	Household	2026-08-23 00:43:34.837187
906	t	2026-08-23 00:43:05.988326	Rice and grains	Pantry Staples	2026-08-23 00:43:05.988326
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_items (id, price, quantity, order_id, product_id) FROM stdin;
193	500.00	3	176	1599
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.orders (id, created_at, delivery_address, order_status, order_type, pickup_date, pickup_time_slot, total_amount, updated_at, user_id) FROM stdin;
176	2026-08-23 00:43:05.992524	123 Main St	COMPLETED	DELIVERY	\N	\N	1500.00	2026-08-23 00:43:05.992524	2896
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.products (id, active, created_at, description, image_url, name, price, stock, updated_at, category_id) FROM stdin;
1600	t	2026-08-23 00:43:34.868913	Superior quality 100% pure whole wheat stone ground chakki fresh atta.	https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80	Aashirvaad Superior MP Atta (10kg)	440.00	35	2026-08-23 00:43:34.868913	906
1601	t	2026-08-23 00:43:34.880742	Light and healthy refined sunflower cooking oil enriched with vitamins.	https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80	Fortune Sunlite Sunflower Oil (1L)	145.00	40	2026-08-23 00:43:34.880742	906
1602	t	2026-08-23 00:43:34.888199	Desh ka Namak, pure vacuum evaporated iodized cooking salt.	https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=600&q=80	Tata Salt Vacuum Evaporated (1kg)	28.00	60	2026-08-23 00:43:34.888199	906
1603	t	2026-08-23 00:43:34.894767	Natural, unpolished, high-protein Arhar / Toor Dal with rich wholesome taste.	https://images.unsplash.com/photo-1585994192701-f1a505c8574a?auto=format&fit=crop&w=600&q=80	Tata Sampann Toor Dal (1kg)	175.00	45	2026-08-23 00:43:34.894767	906
1604	t	2026-08-23 00:43:34.902889	Aromatic blend of roasted exotic Indian spices for authentic curries.	https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80	Everest Royal Garam Masala (100g)	88.00	40	2026-08-23 00:43:34.902889	906
1605	t	2026-08-23 00:43:34.910962	Low temperature ground vibrant red spicy and flavorful Indian chilli powder.	https://images.unsplash.com/photo-1627042633145-b780d842ba45?auto=format&fit=crop&w=600&q=80	Catch Red Chilli Powder (200g)	92.00	45	2026-08-23 00:43:34.910962	906
1606	t	2026-08-23 00:43:34.918713	Zesty tangy seasoning spice blend for salads, snacks, and street food.	https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80	MDH Chunky Chat Masala (100g)	75.00	40	2026-08-23 00:43:34.918713	906
1607	t	2026-08-23 00:43:34.92647	Rich pure natural golden honey for daily immunity and wellness.	https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80	Dabur 100% Pure Honey Squeezy (400g)	199.00	35	2026-08-23 00:43:34.92647	906
1608	t	2026-08-23 00:43:34.933793	Sweet and juicy premium Ratnagiri Alphonso mangoes.	https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80	Fresh Alphonso Mangoes (1kg)	299.00	40	2026-08-23 00:43:34.933793	907
1609	t	2026-08-23 00:43:34.941495	Crisp, sweet, and freshly harvested red Shimla apples.	https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80	Shimla Royal Apple (1kg)	180.00	50	2026-08-23 00:43:34.941495	907
1610	t	2026-08-23 00:43:34.947699	Naturally ripened, potassium-rich fresh yellow bananas.	https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80	Robusta Bananas (1 Dozen)	60.00	60	2026-08-23 00:43:34.947699	907
1611	t	2026-08-23 00:43:34.954476	Grade-A unwashed farm fresh local potatoes for daily cooking.	https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80	Farm Fresh Potatoes (2kg)	70.00	80	2026-08-23 00:43:34.954476	908
1612	t	2026-08-23 00:43:34.963	Firm, juicy, farm-picked red ripe cooking tomatoes.	https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80	Hybrid Red Tomatoes (1kg)	45.00	50	2026-08-23 00:43:34.963	908
1613	t	2026-08-23 00:43:34.969069	Pungent, dry, and quality sorted red onions.	https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80	Fresh Red Onions (2kg)	85.00	70	2026-08-23 00:43:34.969069	908
1614	t	2026-08-23 00:43:34.977371	Pasteurized homogenized toned milk rich in calcium and protein.	https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80	Amul Taaza Toned Milk (1L)	54.00	45	2026-08-23 00:43:34.977371	909
1615	t	2026-08-23 00:43:34.98533	Delicious, creamy salted butter made from fresh pure milk cream.	https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80	Amul Pasteurized Butter (500g)	275.00	35	2026-08-23 00:43:34.98533	909
1616	t	2026-08-23 00:43:34.989915	Soft, tender, high-protein cottage cheese cubes.	https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80	Fresh Malai Paneer (200g)	95.00	30	2026-08-23 00:43:34.989915	909
1617	t	2026-08-23 00:43:34.996765	Rich blend of fine Assam tea leaves with gently rolled long leaves.	https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80	Tata Tea Gold Leaf Tea (500g)	310.00	40	2026-08-23 00:43:34.996765	910
1618	t	2026-08-23 00:43:35.000947	Taste of togetherness, blended with quality Assam CTC black tea leaves.	https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=600&q=80	Brooke Bond Red Label Tea (1kg)	490.00	35	2026-08-23 00:43:35.000947	910
1619	t	2026-08-23 00:43:35.008896	100% pure natural coffee made from roasted Robusta beans.	https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80	Nescafe Classic Instant Coffee (100g Jar)	340.00	30	2026-08-23 00:43:35.008896	910
1620	t	2026-08-23 00:43:35.01279	No added sugar, natural blended juice from premium real fruits.	https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80	Real Active 100% Mixed Fruit Juice (1L)	130.00	25	2026-08-23 00:43:35.01279	910
1621	t	2026-08-23 00:43:35.021759	India's favorite instant masala noodles made with goodness of iron.	https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80	Maggi 2-Minute Noodles (12-Pack)	168.00	50	2026-08-23 00:43:35.021759	911
1622	t	2026-08-23 00:43:35.028123	Crispy, spiced moth bean flour crunchy savory Indian snack.	https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80	Haldiram's Bhujia Sev (400g)	115.00	50	2026-08-23 00:43:35.028123	911
1623	t	2026-08-23 00:43:35.033986	Crispy ridged potato chips seasoned with authentic Indian spices.	https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80	Lay's India's Magic Masala Chips (115g)	50.00	60	2026-08-23 00:43:35.033986	911
1624	t	2026-08-23 00:43:35.040471	Smoother, creamier, and richer melt-in-mouth milk chocolate.	https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=600&q=80	Cadbury Dairy Milk Silk Chocolate (150g)	175.00	40	2026-08-23 00:43:35.040471	911
1625	t	2026-08-23 00:43:35.046352	Made with 100% real ripe juicy tomatoes, tangy and sweet table sauce.	https://images.unsplash.com/photo-1607349913338-fca6f7fc42d0?auto=format&fit=crop&w=600&q=80	Kissan Fresh Tomato Ketchup (950g)	135.00	30	2026-08-23 00:43:35.046352	911
1626	t	2026-08-23 00:43:35.051592	Freshly baked high-fiber 100% whole wheat sliced brown bread.	https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80	Britannia 100% Whole Wheat Bread (400g)	50.00	30	2026-08-23 00:43:35.051592	912
1627	t	2026-08-23 00:43:35.056817	Rich crunchy crust cookies with molten velvety choco lava core.	https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80	Sunfeast Dark Fantasy Choco Fills (300g)	120.00	40	2026-08-23 00:43:35.056817	912
1599	t	2026-08-23 00:43:05.99023	Long grain aged rice	https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80	Premium Basmati 5kg	500.00	20	2026-08-23 00:43:05.99023	906
1628	t	2026-08-23 00:43:35.062238	Crispy golden corn flakes enriched with sliced crunchy almonds and honey.	https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?auto=format&fit=crop&w=600&q=80	Kelloggs Real Almond Corn Flakes (1kg)	425.00	25	2026-08-23 00:43:35.062238	912
1629	t	2026-08-23 00:43:35.068111	Trusted antiseptic germ protection moisturizing skin bath soap.	https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=600&q=80	Dettol Original Germ Protection Soap (4 x 125g)	195.00	35	2026-08-23 00:43:35.068111	913
1630	t	2026-08-23 00:43:35.073036	12-hour antibacterial whole mouth protection for teeth and gums.	https://images.unsplash.com/photo-1559591937-e62fb330bc1f?auto=format&fit=crop&w=600&q=80	Colgate Total Advanced Health Toothpaste (240g)	210.00	40	2026-08-23 00:43:35.073036	913
1631	t	2026-08-23 00:43:35.078999	Advanced stain removal formula specially designed for washing machines.	https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?auto=format&fit=crop&w=600&q=80	Surf Excel Matic Top Load Detergent (2kg)	430.00	30	2026-08-23 00:43:35.078999	914
1632	t	2026-08-23 00:43:35.085473	Concentrated lemon degreasing liquid gel for sparkling clean utensils.	https://images.unsplash.com/photo-1585670270608-b4be4fbcf05d?auto=format&fit=crop&w=600&q=80	Vim Lemon Dishwash Gel (750ml Bottle)	155.00	45	2026-08-23 00:43:35.085473	914
1633	t	2026-08-23 00:49:24.393649	Aged long-slender grain fragrant Basmati rice for daily aromatic meals.	https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80	India Gate Basmati Rice Rozzana (5kg)	480.00	40	2026-08-23 00:49:24.393649	906
1634	t	2026-08-23 00:49:24.393649	Cold pressed pure pungent mustard oil enriched with omega-3.	https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80	Fortune Pure Mustard Oil (1L)	155.00	35	2026-08-23 00:49:24.393649	906
1635	t	2026-08-23 00:49:24.393649	Nutritious, protein-rich unpolished yellow split moong lentils.	https://images.unsplash.com/photo-1585994192701-f1a505c8574a?auto=format&fit=crop&w=600&q=80	Tata Sampann Moong Dal Split (1kg)	165.00	40	2026-08-23 00:49:24.393649	906
1636	t	2026-08-23 00:49:24.393649	100% pure Chana Dal ground fine besan for snacks and sweets.	https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80	Rajdhani Pure Besan (1kg)	95.00	50	2026-08-23 00:49:24.393649	906
1637	t	2026-08-23 00:49:24.393649	Traditional pure cow ghee with natural aroma and golden granules.	https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80	Patanjali Pure Cow Desi Ghee (1L)	650.00	30	2026-08-23 00:49:24.393649	906
1638	t	2026-08-23 00:49:24.393649	Rich curcumin high-quality ground fragrant yellow turmeric.	https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80	Everest Turmeric Haldi Powder (200g)	62.00	55	2026-08-23 00:49:24.393649	906
1639	t	2026-08-23 00:49:24.393649	Fresh aromatic ground coriander seeds seasoning powder.	https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80	Catch Coriander Dhaniya Powder (200g)	58.00	50	2026-08-23 00:49:24.393649	906
1640	t	2026-08-23 00:49:24.393649	Rich creamy pasteurized whole milk with 6% fat and 9% SNF.	https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80	Amul Gold Full Cream Milk (1L)	68.00	50	2026-08-23 00:49:24.393649	909
1641	t	2026-08-23 00:49:24.393649	Thick, creamy, and probiotic fresh natural set dahi.	https://images.unsplash.com/photo-1571212515416-fef01fc43637?auto=format&fit=crop&w=600&q=80	Mother Dairy Classic Dahi (400g)	40.00	45	2026-08-23 00:49:24.393649	909
1642	t	2026-08-23 00:49:24.393649	Rich delicious melted cheese slices for sandwiches and burgers.	https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=600&q=80	Amul Processed Cheese Slices (200g)	145.00	35	2026-08-23 00:49:24.393649	909
1643	t	2026-08-23 00:49:24.393649	Zero calorie soothing natural antioxidant-rich green tea bags.	https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=600&q=80	Lipton Pure Green Tea (100 Bags)	320.00	30	2026-08-23 00:49:24.393649	910
1644	t	2026-08-23 00:49:24.393649	Aromatic South Indian blend of roasted coffee and chicory.	https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80	Bru Instant Coffee Chicory Mix (200g)	380.00	25	2026-08-23 00:49:24.393649	910
1645	t	2026-08-23 00:49:24.393649	Iconic juicy and sweet ripe mango fruit juice beverage.	https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80	Frooti Fresh Mango Drink (1.2L)	75.00	40	2026-08-23 00:49:24.393649	910
1646	t	2026-08-23 00:49:24.393649	Crispy spiced potato and gram flour savory Indian snack.	https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80	Haldirams Aloo Bhujia (400g)	110.00	50	2026-08-23 00:49:24.393649	911
1647	t	2026-08-23 00:49:24.393649	Tedha hai par mera hai, chatpata spicy crunchy snack sticks.	https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80	Kurkure Masala Munch (90g)	20.00	60	2026-08-23 00:49:24.393649	911
1648	t	2026-08-23 00:49:24.393649	India's favorite golden crispy glucose biscuits for daily tea.	https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80	Parle-G Gold Glucose Biscuits (1kg)	95.00	55	2026-08-23 00:49:24.393649	911
1649	t	2026-08-23 00:49:24.393649	Delightful buttery cookies with rich smile-pattern texture.	https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80	Britannia Good Day Butter (600g)	140.00	45	2026-08-23 00:49:24.393649	911
1650	t	2026-08-23 00:49:24.393649	Clinically proven up to 100% flake-free smooth shiny hair formula.	https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80	Head & Shoulders Smooth Shampoo (650ml)	499.00	25	2026-08-23 00:49:24.393649	913
1651	t	2026-08-23 00:49:24.393649	Kills 99.9% of germs without water, rinse-free protection.	https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?auto=format&fit=crop&w=600&q=80	Dettol Instant Hand Sanitizer (200ml)	99.00	50	2026-08-23 00:49:24.393649	913
1652	t	2026-08-23 00:49:24.393649	Thick liquid formula for 99.9% germ kill and tough stain removal.	https://images.unsplash.com/photo-1585670270608-b4be4fbcf05d?auto=format&fit=crop&w=600&q=80	Harpic Power Plus 10X Max (1L)	195.00	40	2026-08-23 00:49:24.393649	914
1653	t	2026-08-23 00:49:24.393649	Tri-action floor cleaning formula with 99.9% germ protection.	https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?auto=format&fit=crop&w=600&q=80	Lizol Citrus Floor Cleaner (2L)	365.00	30	2026-08-23 00:49:24.393649	914
1654	t	2026-08-23 00:49:24.393649	Long lasting fragrance and unbeatable shine for washed clothes.	https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?auto=format&fit=crop&w=600&q=80	Comfort Morning Fresh Conditioner (860ml)	240.00	35	2026-08-23 00:49:24.393649	914
\.


--
-- Data for Name: return_requests; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.return_requests (id, created_at, reason, staff_comment, status, type, updated_at, order_id, user_id, note, quantity, order_item_id) FROM stdin;
60	2026-08-23 00:43:05.996192	Product Expired	\N	REQUESTED	RETURN	2026-08-23 00:43:05.996192	176	2896	\N	1	193
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, active, created_at, email, name, password, phone, role, updated_at) FROM stdin;
2896	t	2026-08-23 00:43:05.529487	alice.return@dmart.com	Alice Return	$2a$10$zkmsq1u6WZVy5Zl.AEB63u/4JWlncRxooW9DT0/XUR1SRwcoyBbWO	\N	CUSTOMER	2026-08-23 00:43:05.529487
2897	t	2026-08-23 00:43:05.677447	bob.return@dmart.com	Bob Return	$2a$10$.3n1x480frq.RDF.kHi4aOWjjJxu55OxNqFKduNJ9WmKECQboPgRi	\N	CUSTOMER	2026-08-23 00:43:05.677447
2898	t	2026-08-23 00:43:05.831973	staff.return@dmart.com	Staff Return	$2a$10$svkp4AySMOapTnDH853/ouLS0QHWQODCxYbmG6Z5R.Au97EbIioO6	\N	STAFF	2026-08-23 00:43:05.831973
2899	t	2026-08-23 00:43:05.980998	admin.return@dmart.com	Admin Return	$2a$10$YDiPwOcOsNyvcgmvUGj88.LN7w7DLeUcyIeW2WWQWwVpvOX8SqApW	\N	ADMIN	2026-08-23 00:43:05.980998
\.


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.audit_logs_id_seq', 1, false);


--
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 224, true);


--
-- Name: carts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.carts_id_seq', 283, true);


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.categories_id_seq', 914, true);


--
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_items_id_seq', 193, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.orders_id_seq', 176, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.products_id_seq', 1654, true);


--
-- Name: return_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.return_requests_id_seq', 60, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 2899, true);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: return_requests return_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT return_requests_pkey PRIMARY KEY (id);


--
-- Name: carts uk64t7ox312pqal3p7fg9o503c2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: cart_items uk_cart_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT uk_cart_product UNIQUE (cart_id, product_id);


--
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: return_requests fk6pd9hi2rbbct43io2pgcma1sh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fk6pd9hi2rbbct43io2pgcma1sh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: carts fkb5o626f86h46m4s7ms6ginnop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fkb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: return_requests fkbski88d6kewx0cbj5pk7nes01; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fkbski88d6kewx0cbj5pk7nes01 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: audit_logs fkjs4iimve3y0xssbtve5ysyef0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fkjs4iimve3y0xssbtve5ysyef0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: order_items fkocimc7dtr037rh4ls4l95nlfi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: return_requests fkqmtolfa50ie1jxfsak1e8jnkb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fkqmtolfa50ie1jxfsak1e8jnkb FOREIGN KEY (order_item_id) REFERENCES public.order_items(id);


--
-- PostgreSQL database dump complete
--

\unrestrict AddwHtsQxcNHgV6VMrpf3QAzsFBcNHGTdlbLKIsoRZn1Tz6cjOEpEqx0iGsuAeM

